channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - ucsc-wigtobigwig=366
  - jupyter=1.0.0
  - kallisto=0.45.0
  - picard=2.18.26
  - bedtools=2.27.1
  - blast=2.7.1
  - jupyterlab
  - samtools=1.9
  - python=3.6
  - umi_tools=0.5.5
  - tqdm=4.31.1
  - python-igraph=0.7.1
  - hisat2=2.1.0
  - ucsc-bedgraphtobigwig=366
  - matplotlib-venn=0.11.5
  - fastqc=0.11.8
  - star=2.7.0b
  - scipy=1.2.0
  - pandas=0.24.1
  - pybedtools=0.8.0
  - homer=4.9.1
  - pygraphviz=1.3.1
  - scikit-learn=0.20.2
  - ucsc-bedtobigbed=366
  - ucsc-liftover=366
  - tensorflow=1.10.0
  - ipykernel=5.1.0
  - rsem=1.2.28
  - pysam=0.15.2
  - pybigwig=0.3.13
  - ipywidgets=7.4.2
  - mirdeep2=2.0.0
  - nodejs=9.11.1
  - sailfish=0.10.1
  - seaborn=0.9.0
  - bowtie2=2.3.4.3
  - biopython=1.73
  - awscli=1.16.106
  - idr=2.0.4
  - ucsc-bigwigtobedgraph=366
  - gffutils=0.9
  - bowtie=1.2.2
  - numpy=1.16.1
  - pyyaml=3.13
  - igraph=0.7.1
  - fastx_toolkit=0.0.14
  - matplotlib
  - deeptools=3.1.3
  - seqtk=1.3
  - emboss=6.6
  - subread=1.6.3
  - salmon=0.12.0
  - bcftools=1.9
  - graphviz=2.38.0
  - cutadapt=1.18
