name: skipper-clipper-compare
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - bedtools=2.31.1
  - pybedtools=0.12.0
  - pandas=2.2.3
  - numpy=2.2.6
  - scipy=1.15.2
  - matplotlib-base=3.10.3
  - seaborn-base=0.13.2
  - matplotlib-venn=1.1.2
